# kubernetes-manifests/ms-agenda.yaml

# 1. Service (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: ms-agenda-service
  labels:
    app: ms-agenda
spec:
  selector:
    app: ms-agenda
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
---

# 2. Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-agenda-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-agenda
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: ms-agenda
    spec:
      containers:
        - name: ms-agenda
          image: ms-agenda:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          env:
            # --- Variables de la Aplicación ---
            - name: PORT
              value: "3002"

            # --- Variables de Seguridad (JWT) ---
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: JWT_EXPIRES_IN
              value: "1h"

            # --- Conexión a la Base de Datos ---
            - name: DB_HOST
              value: "db-agenda"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-agenda-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-agenda-secret
                  key: password
            - name: DB_NAME
              value: "db_agenda"

            # --- Conexión a RabbitMQ ---
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_URL
